name: 'modeling'
version: '1.0.0'
config-version: 2

profile: 'postgres_dwh_profile'

model-paths: ["models"]

clean-targets:    # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  modeling:
    analytics:
      +materialized: table


